config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  delete "tasks/:id", to: "tasks#destroy"
  get "edit/:id", to: "tasks#edit", as: :edit
  patch "tasks/:id", to: "tasks#update", as: :update
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(title: params[:task][:title], details: params[:task][:details])
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(format)
    redirect_to tasks_path
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end
end

private

def format
  params.require(:task).permit(:title, :details)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_controller_helper.rb
module TasksControllerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h2>Editing ☑ :</h2>
  <p>
   <%= form_for(@task) do |t| %>
      <div class="form-group">
        <%= t.label :title %>
        <%= t.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= t.label :details %>
        <%= t.text_field :details, class: 'form-control' %>
      </div>

      <button type="button" class="btn btn-light"> <%= link_to "Go Back", tasks_path %></button>

      <%= t.submit class: 'btn btn-danger' %>
    <% end %>
    </p>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Things you probably should have done yesterday:</h1>
  <p>
    <ul>
      <% @tasks.each do |task| %>
      <li>
        <%= link_to task.title, task_path(task.id) %>
        <%= link_to " - [Destroy me]", task_path(task.id), method: :delete, data: { confirm: "Are you sure?" } %>
        </li>
      <% end %>
    </ul>
  </p>
  <hr>
<button type="button" class="btn btn-light"><%= link_to "Add new task ͢ ", tasks_new_path  %></button>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <h2>Add new task ☑ :</h2>
  <p>
   <%= form_for(@task) do |t| %>
      <div class="form-group">
        <%= t.label :title %>
        <%= t.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= t.label :details %>
        <%= t.text_field :details, class: 'form-control' %>
      </div>

      <button type="button" class="btn btn-light"> <%= link_to "Go Back", tasks_path %></button>

      <%= t.submit class: 'btn btn-danger' %>
    <% end %>
    </p>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <hr>
  <h2>Task details:</h2>
  <hr>
  <h3><%= @task.title %></h3>
  <p><%= @task.details %></p>
  <button type="button" class="btn btn-light"><%= link_to "Back to tasks", tasks_path %></button>
  <button type="button" class="btn btn-warning"><%= link_to "Edit", edit_path %></button>
</div>